register-object:
    batch_limit: 1000
    error_limit: 5

descriptive-metadata:
    prerequisite: register-object
    batch_limit: 1000
    error_limit: 10

google-convert:
    prerequisite: register-object
    batch_limit: 1
    error_limit: 5

google-download:
    prerequisite: descriptive-metadata
    batch_limit: 1000
    error_limit: 10

virus-scan:
    prerequisite: google-download
    batch_limit: 1000
    error_limit: 10

process-content:
    prerequisite: google-download
    batch_limit: 1000
    error_limit: 10

sdr-ingest-transfer:
    prerequisite: process-content
    batch_limit: 1000
    error_limit: 10

sdr-ingest-deposit:
    prerequisite:  sdr-ingest-transfer
    batch_limit: 1
    error_limit: 5

shelve:
    prerequisite:  process-content
    batch_limit: 1
    error_limit: 5

cleanup:
    prerequisite: sdr-ingest-deposit, shelve
    batch_limit: 1
    error_limit: 5
    
sdr-ingest-archive:
    prerequisite:  sdr-ingest-transfer
    batch_limit: 1
    error_limit: 5

repository: dor

